server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-service
              uri: http://localhost:8085
              predicates:
                - Path=/identity-service/**
              filters:
                - StripPrefix=1

            - id: game-service
              uri: http://localhost:8082
              predicates:
                - Path=/game-service/**
              filters:
                - StripPrefix=1

            - id: theme-service
              uri: http://localhost:8086
              predicates:
                - Path=/theme-service/**
              filters:
                - StripPrefix=1

            - id: social-service
              uri: http://localhost:8087
              predicates:
                - Path=/social-service/**
              filters:
                - StripPrefix=1

            - id: matchmaking-service
              uri: http://localhost:8090
              predicates:
                - Path=/matchmaking-service/**
              filters:
                - StripPrefix=1

            - id: profile-service
              uri: http://localhost:8088
              predicates:
                - Path=/profile-service/**
              filters:
                - StripPrefix=1

            - id: leaderboard-service
              uri: http://localhost:8091
              predicates:
                - Path=/leaderboard-service/**
              filters:
                - StripPrefix=1

            - id: game-service-ws
              uri: ws://localhost:8082
              predicates:
                - Path=/game-service/ws
              filters:
                - StripPrefix=1

            - id: social-service-ws
              uri: ws://localhost:8087
              predicates:
                - Path=/social-service/ws
              filters:
                - StripPrefix=1

            - id: matchmaking-service-ws
              uri: ws://localhost:8090
              predicates:
                - Path=/matchmaking-service/ws
              filters:
                - StripPrefix=1

            - id: profile-service-ws
              uri: ws://localhost:8088
              predicates:
                - Path=/profile-service/ws
              filters:
                - StripPrefix=1

logging:
  level:
    io.github.quizup: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.apache.kafka: OFF
    org.springframework.kafka: OFF
